#------------------------------------------------------------------------------

SOURCE=main.cpp # octhecdec.h
MYPROGRAM=fuzzysearch

CC=g++

#------------------------------------------------------------------------------



all: $(MYPROGRAM)



$(MYPROGRAM): $(SOURCE)

	$(CC) $(SOURCE) -o $(MYPROGRAM)

clean:

	rm -f $(MYPROGRAM) *.o

